# 4:25 AM [ Alarm goes off]
I wake up, Christian Fanli yells "zhu Zhuang!", I put my eye blinder and ear plugs away. Here we go, another day. Let's see what is possible. Fanli gets out first and then I jump on his back. Fanli carries me to the restroom.

# 4:30 AM Morning Read [ Alarm goes off] 
I open E.T. Jaynes Probability - logic of science notebook
# 6:30 AM Day Prep ( Review, Meal Prep, Getting Dressed)

# 7:00 AM Lecture 

# 7:30 - 8:30 AM Ban Kuai Yi Programming Tasks
# 8:30 - 8:35 Survey + survey review

# 8:35 - 9:10 Finish up 
# 9:10 - 9:40 MIT Computation Lecture
# 9:40 - 9:55 Quick Run / Stretch
# 10:00 - 11:40  AM Ban Kuai Er Programming Tasks
# 11:40 - 11:40 AM Survey

11;40-12;00. Makes c compliments to Ramon

Hello Jie, I hope you are doing well.
After speaking with Christian Fanli over the past weeks my interest has grown in moving to Shanghai and also working with a company that fits our longer-term goals for impact in helping be a part of the shift towards more ecological awareness and impact and awareness. I would be very interested in working alongside Christian Fanli and use our machine learning skills at a place like Envision.

He has told me about you and how you guys have much in common and that you have helped the team find clarity.

I have attached my resume below.

Christian Fanli and I have a few sites we use daily and I think it shows how committed we are to this topic. 

https://haohanwang.tumblr.com/ - my life blog, after taking 1.5 years off to create a course, start writing a book, and finish a few studies around human behavior I started studying outside of finance and self-studying human behavior and algorithms to show that I could be self-reliant without a company or university.

Most recently I've been working on machine learning algorithms for a neurobiology lab out of Stanford called Huberman, where Christian Fanli and I are predicting anxiety, fear, and depression from patients in VR given a stimulus.

Life blog -
Musings of a deep learning student on a mission
haohanwang.tumblr.com
 
Huberman Lab at Stanford - 
https://stanmed.stanford.edu/2017summer/huberman-virtual-reality-curing-fear-anxiety.html

Andrew Huberman on using virtual reality to cure fears, no matter what you see
stanmed.stanford.edu


Applied Deep Learning with TensorFlow course
https://www.oreilly.com/library/view/applied-deep-learning/9781788621601/
Applied Deep Learning with TensorFlow and Google Cloud AI
oreilly.com

Lastly, here is a link to our recent work. https://dyadxmachina.github.io/hub/

dyadxmachina projects: dyad x machina projects
dyadxmachina.github.io

For reference, 'dyad x machina' is Christian Fanli's and myself's public commitment to human and ecological betterment so we publish our public work at this site.

I am looking forward to speaking with you on Monday.